- README.md
The app is now available via flathub :tada:. Add instructions on how to install.
I strongly recommend migrating to the flathub version in order to receive updates in the future.
Closes #6
> Add Flathub link to README

- src/exm-window.blp
- src/exm-window.c
- src/model/exm-manager.c
This makes it clear which extensions the user can remove and which are distributed by the system.
Fixes #12
> Show system extensions separately from user extensions

- src/exm-window.c
When creating the extension model, sort alphabetically by the first letter of the extension's display name.
Fixes #13
> Sort extensions alphabetically

- data/com.mattjakeman.ExtensionManager.gschema.xml
- src/exm-application.c
- src/exm-window.blp
- src/exm.gresource.xml
- Let the user override the system dark preference from within the app.
- Properly support dark mode by making sure symbolic icons are recoloured correctly.
Fixes #7 
Some images:
> Add support for Dark Mode

- src/exm-window.blp
- src/exm-window.c
Adds a callback to the search entry which triggers the default search. This should avoid extraneous calls to extensions.gnome.org where they are not necessary. For example, for users who open the application only to manage local extensions.
Part of #33
> Only trigger search once browse tab is loaded

- src/exm-window.blp
- src/exm-window.c
Show a placeholder 'spinner' while search results are processing. Once loaded, display the results instead. This will provide some level of user feedback about the search state and avoid visual bugs when no search results are present.
Part of #33
> Search: Add search progress indicator

- src/exm-window.blp
- src/exm-window.c
- Adds a toggle which globally enables/disables shell extensions.
- When extensions are globally disabled, the list boxes are made insensitive.
This might not be the most desirable behaviour (e.g. a user may wish to disable extensions globally, then uninstall some while extensions are off). However this is better than having no toggle at all, and is a good first step.
Fixes #11 
Depends on #37 and #38
> Add global extension toggle

- po/POTFILES
- po/extension-manager.pot
- src/exm-browse-page.blp
- src/exm-browse-page.c
- src/exm-browse-page.h
- src/exm-extension-row.blp
- src/exm-extension-row.c
- src/exm-extension-row.h
- src/exm-installed-page.blp
- src/exm-installed-page.c
- src/exm-installed-page.h
- src/exm-search-row.blp
- src/exm-search-row.c
- src/exm-search-row.h
- src/exm-window.blp
- src/exm-window.c
- src/exm.gresource.xml
- src/local/exm-extension.c
- src/local/exm-extension.h
- src/local/exm-manager.c
- src/local/exm-manager.h
- src/meson.build
- Six strings added, none removed
This will make the GUI more maintainable and paves the way for #3.
Incidentally, it is also significantly faster as the listbox is not recreated each time an update occurs.
> The big GUI refactor

- src/exm-window.c
- src/local/exm-manager.c
- src/web/exm-search-provider.c
- src/web/model/exm-shell-version-map.c
- src/web/model/exm-shell-version-map.h
Hide debug output by default. This will help actual errors be more easily distinguished.
> Cleanup console output

- src/exm-browse-page.blp
- src/exm-browse-page.c
- src/web/exm-search-provider.c
- src/web/exm-search-provider.h
Allow filtering search results by:
- Popularity
- Downloads
- Name
- Recent
Just like the extensions.gnome.org website
Part of #33
> Add support for sorting search results

- src/exm-browse-page.blp
- src/exm-browse-page.c
- src/exm-detail-view.blp
- src/exm-detail-view.c
- src/exm-search-row.c
- src/exm-search-row.h
- src/exm-window.c
- src/style.css
- src/web/meson.build
- src/web/model/exm-search-result.c
- src/web/model/exm-search-result.h
- src/web/model/exm-shell-version-map.c
- src/web/model/exm-shell-version-map.h
Parse the shell_version_map json object and use this to determine whether the extension is installable.
If not supported, display the following message and tooltip:
TODO:
Fixes #5
> Only allow the installation of compatible extensions

- src/exm-detail-view.c
- src/exm-search-row.c
- src/exm-window.blp
This is necessary as some languages have different words for e.g. "Installed [Extensions]" (plural) and "[It is] Installed" (singular). New contextual strings for other instances of this can be added as and when needed.
Fixes #112
> i18n: Add context to various translation strings

- data/meson.build
Official distro build machines often don't have internet access but distros often still like to run all available build tests.
> project: Don't require internet access for appstream validate test

- src/exm-installed-page.c
- src/style.css
Add a placeholder label when no extensions are installed.
Fixes #63
> installed-page: Add placeholder labels with no extensions installed

- data/com.mattjakeman.ExtensionManager.gschema.xml.in
- src/exm-application.c
- src/exm-extension-row.c
- src/exm-installed-page.c
- src/exm-window.blp
- src/local/exm-manager.c
> Add option to sort extensions by enabled status

- NEWS
- src/exm-window.blp
- src/release-notes.txt
- src/style.css
- Declare new dependency in NEWS file
- Fix duplicate menu entry
- Remove reference to placeholder text
Looks like the placeholder text code got lost in 447675b4f54da79bf9ba9f7e18ace58956386dcd. It'll have to wait for now, since I've promised no changes to strings...  :/
> project: Minor fixes for 0.3

- src/local/exm-extension.c
- Escape special characters in the display name and description
- Resolves markup escaping problems once and for all (hopefully)
Fixes #173
> Fix special character escaping

- src/exm-window.c
Goes against GNOME HIG. It's also quite annoying.
The release notes menu entry is still here, at least until software centres can show release notes more reliably.
TODO:
Fixes #153
> Remove release notes popup dialog on startup

- data/meson.build
I missed one detail from fdf8675ad
https://freedesktop.org/software/appstream/docs/sect-Metadata-Application.html
> metainfo: Update for standard install location, part two

- NEWS
- README.md
- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
- meson.build
- src/release-notes.txt
Last of the 0.3.x series - now on to 0.4 🎉
- Lots of translation updates
- Some minor fixes
> Release version 0.3.2

- .github/workflows/main.yml
- com.mattjakeman.ExtensionManager.Devel.json
- meson.build
- src/exm-application.c
- Bump version to 0.4
- Pin blueprint-compiler at version 0.2.0
- Use GNOME nightly SDK
- Port about dialog to AdwAboutWindow
> Post release version bump and misc changes

- data/com.mattjakeman.ExtensionManager.gschema.xml.in
- src/exm-application.c
- src/exm-browse-page.c
- src/exm-window.blp
- src/web/exm-search-provider.c
- Filter out unsupported extensions according to a new 'show-unsupported' setting
- This setting is disabled by _Default_ - users are discouraged from using unsupported extensions, but the option is there if they wish.
Look how blue it is :0
Fixes #114
> Filter out unsupported extensions by default

- src/exm-installed-page.c
- src/exm-window.c
When we have no extensions visible, implement a placeholder.
Fixes #63
> Implement Placeholders

- data/icons/hicolor/meson.build
- data/icons/meson.build
- src/exm-rating.c
- src/exm.gresource.xml
Icons are currently installed in datadir, it can cause conflict with others apps (maybe they are using the same icons). So, i move icons to  `gressource`
> fix: move icons to gressource

- data/com.mattjakeman.ExtensionManager.desktop.in.in
- data/meson.build
- src/exm-application.c
- src/exm-browse-page.c
- src/exm-installed-page.c
- src/exm-screenshot.c
- src/exm-zoom-picture.c
- src/local/exm-extension.c
- src/local/exm-manager.c
- src/main.c
Handle the `gnome-extensions://` uri scheme
Fixes #249
> Implement URI Handler + misc tweaks

- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
Application summary in AppStream metainfo, just like Comment in a desktop file, should not end with a period. See the [example file](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-example).
/cc @mjakeman
> metainfo: Remove period from the summary

- com.mattjakeman.ExtensionManager.Devel.json
- meson.build
- meson_options.txt
- src/exm-error-dialog.blp
- src/exm-error-dialog.c
Since a lot of third-party packages are doing interesting and funky things, differentiate between upstream and third-party packages in the support log.
We'll still take bug reports for third-party packages, but users are encouraged to go to the distribution first since it's (probably) not an upstream problem.
> Changes to error/support log generation

- src/exm-upgrade-assistant.blp
Unless you have a rather strange idea about how that scroll should work, I honestly think you don't want it to be able to scroll horizontally.
> upgrade-assistant: don't scroll horizontally on results

- src/exm-backtrace.c
The file uses type `uintptr_t` from `stdint.h`, which is indirectly included by `backtrace.h`.  Even so, the file should unconditionally include `stdint.h` just in case `backtrace.h` no longer includes `stdint.h` in the future.
> exm-backtrace.c: Explicitly include stdint.h for uintptr_t usage

- src/exm-installed-page.c
Closes https://github.com/mjakeman/extension-manager/issues/388
[Screencast from 2023-06-25 16-20-03.webm](https://github.com/mjakeman/extension-manager/assets/50847364/47c967c0-162b-477e-b737-b2146b69eab6)
> Use `active` instead of `state` for global toggle

- .github/workflows/main.yml
- Bump `actions/checkout` from `v2` (Node 12) to `v3` (Node 16). [Node 12 reached eol recently, GitHub removed support for it last month, currently, all runners default to Node 16 even if the file has Node 12 specified.]
- Bump `bilelmoussaoui/flatpak-github-actions/flatpak-builder` to `v6.1`.
> CI: bump actions version, fix Node 12 deprecation warning under action runs

- meson.build
- meson_options.txt
- src/exm-application.c
- src/exm-backtrace.c
- src/meson.build
libbacktrace is not available in some distributions where Extension Manager is available as a native package, e.g. [Gentoo], [Debian].  Yet the backtraces that libbacktrace helps to collect are vital information for a crash report.
To help both these distributions continue shipping Extension Manager as a native package and users who install this app via Flathub report crashes with backtraces, I have created this patch to make libbacktrace an optional dependency.  It introduces a new `backtrace` Meson boolean option, which controls whether Extension Manager is to be built with libbacktrace.  It is set to `true` by default, so existing build pipelines, e.g. [this repo's GitHub Action workflow](https://github.com/mjakeman/extension-manager/actions/workflows/main.yml), behave the same as …
> Make libbacktrace an optional dependency

- src/exm-extension-row.blp
This pull request adds margins to out-of-date, error, update icon in local installed extensions list to align it with preferences button.
Result of this PR:
> Use proper margins for icons in local extensions list

- src/exm-upgrade-assistant.c
> upgrade-assistant: Mark two strings as translatable

- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
These changes will not appear until flatpak-builder 1.4.x, which uses libappstream instead of appsteam-glib, is released and Flathub's buildbot rebuilds it with that version.
| master | PR |
|-|-|
| ![Captura desde 2023-08-20 00-01-20](https://github.com/mjakeman/extension-manager/assets/42654671/3efb6af3-bea3-4596-9a7a-b6d7e2209a84) | ![Captura desde 2023-08-20 00-05-36](https://github.com/mjakeman/extension-manager/assets/42654671/d388abdd-b584-4f9a-a35e-0d0aff26c053) |
> metainfo: Add supports and requires tags

- src/exm-browse-page.c
- src/exm-detail-view.c
- src/exm-error-dialog.c
- src/exm-extension-row.blp
- src/exm-extension-row.c
- src/exm-installed-page.c
- src/exm-upgrade-assistant.c
- src/exm-window.c
- src/exm-zoom-picture.c
Wording could probably be improved.
|Uninstall extension dialog | Install unsupported extension dialog|
|---------------------|------------------------|
| ![image](https://github.com/mjakeman/extension-manager/assets/42654671/43522d2f-0c1b-49de-85ea-16acf700cbe3) | ![image](https://github.com/mjakeman/extension-manager/assets/42654671/18154c55-789e-40da-bc3c-fedab9570972) |
| ![image](https://github.com/mjakeman/extension-manager/assets/42654671/ab67047a-d1f9-464f-ab04-cfaabe865b63) | ![image](https://github.com/mjakeman/extension-manager/assets/42654671/cc6312ff-8592-49fc-a123-1ff18e0d5690) |
> Replace deprecated methods and widgets

- src/exm-browse-page.blp
- src/exm-browse-page.c
- src/web/exm-search-provider.c
- src/web/exm-search-provider.h
It is used by default for search in extensions web, the rest are somewhat broken.
Fix #478
> search: Add relevance sort type

- com.mattjakeman.ExtensionManager.Devel.json
GNOME Extensions web allows uploading [WebP images](https://gitlab.gnome.org/Infrastructure/extensions-web/-/blob/master/sweettooth/extensions/forms.py?ref_type=heads#L55). `webp-pixbuf-loader` is installed out of the box in distributions like Ubuntu or Fedora, but that is not the case for GNOME SDK as of [now](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/677).
Tested with an [extension](https://extensions.gnome.org/extension/5985/do-not-disturb-while-screen-sharing-or-recording/) that has its icon in that format:
> flatpak: Add WebP support

- src/exm-detail-view.blp
- src/exm-detail-view.c
> detail-view: Hide "Show All Reviews" button when there are none

- src/exm-detail-view.blp
- src/exm-detail-view.c
- src/web/model/exm-search-result.c
See https://gitlab.gnome.org/Infrastructure/extensions-web/-/commit/6090340c180c8662283eecbe5642297261698fe6
Fix #162
> detail-view: Add extension's homepage

- .github/workflows/main.yml
- Bump `actions/checkout` from `v3` to `v4` the changes can be found [here](https://github.com/actions/checkout/compare/v3...v4), this includes **Node 20**
-  Bump `bilelmoussaoui/flatpak-github-actions/flatpak-builder` to `v6.3` from `v6.1`, just so everything is great :+1:
> CI: Bumped Checkout (v4) & Flatpak Builder (v6.3)

- com.mattjakeman.ExtensionManager.Devel.json
The change from `app-id` to `id` is something I have seen in some applications such as [GNOME Calendar](https://github.com/flathub/org.gnome.Calendar/commit/d5077fc54f6d7a76b28e352cdd9bf6203fdf739b).
The second commit is [directly copied](https://github.com/flathub/com.mattjakeman.ExtensionManager/pull/15/commits/544b83af7f09685a951b30a15519567fe839f55b) from the manifest changes in the Flathub repository, although it was reverted in the last update.
Also, the Flathub manifest is missing some config options, such as the distributor and the package type, which are present here.
> flatpak: Update manifest

- po/POTFILES
- src/exm-detail-view.blp
- src/exm-detail-view.c
- src/exm-detail-view.h
- src/exm-info-bar-item.blp
- src/exm-info-bar-item.c
- src/exm-info-bar-item.h
- src/exm-info-bar.blp
- src/exm-info-bar.c
- src/exm-info-bar.h
- src/exm-window.blp
- src/exm-window.c
- src/exm.gresource.xml.in
- src/meson.build
- src/style.css
- src/web/model/exm-search-result.c
> detail-view: Add info bar

- src/exm-comment-tile.blp
- src/exm-comment-tile.c
- src/style.css
- src/web/model/exm-comment.c
Following a similar design to the extensions website.
> comment-tile: Add extension's author badge

- src/exm-detail-view.blp
- src/exm-installed-page.blp
Missed in #458
See https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/property.ActionRow.icon-name.html
> Move from deprecated row icons to prefix and suffix

- data/meson.build
This should be `--no-net`
```
3/3 Validate appstream file        FAIL            0.01s   exit status 1`
...
stdout:
Unknown option --nonet
```
> Syntax Error in data/meson.build: appstreamcli validate --nonet

- src/exm-detail-view.blp
- src/exm-detail-view.c
If the extension has one.
For now it is mostly a duplication of the code that manages screenshots.
> detail-view: Add extension icon

- src/exm-comment-tile.blp
- src/exm-comment-tile.c
Following extensions website behavior. Also covers the case where the author of the comment is the extension's creator.
> comment-tile: Hide rating when zero

- .github/workflows/main.yml
- build-aux/com.mattjakeman.ExtensionManager.Devel.json
- build-aux/com.mattjakeman.ExtensionManager.json
With the master version of the runtime we can test the changes in the development versions of the libraries beforehand.
This also removes `webp-pixbuf-loader` from the modules in the devel manifest, as it will be included in the platform for GNOME 46. See https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/2507
> flatpak: Have stable and devel manifests in tree

- src/exm-extension-row.c
Escaping it here instead of `exm-extension` should hopefully fix extensions with special characters and avoid issues anywhere else.
Fix https://github.com/mjakeman/extension-manager/issues/473
> extension-row: Escape title

- src/exm-search-row.blp
- src/exm-search-row.c
I also took the opportunity to run the new formatter (`blueprint-compiler format`).
It remains to do the same with `extension-row`, which will be better to do in or after #517.
> search-row: Use GtkExpression lookups in Blueprint

- src/exm-upgrade-assistant.c
With the new year, two new versions of GNOME have been added that have not yet been released. To fix this, since the calculation based on the release date of GNOME 40 always results in the first version to be released in March of that year, which is even, then:
- If the month is prior to March, subtract one from the approximation, leaving the odd-numbered version released in September of the previous year.
- If the month is between March and September, we keep the value.
- If the month is September or later, we add one to get the odd numbered version of the year.
> upgrade-assistant: Fix GNOME version calculation

- data/com.mattjakeman.ExtensionManager.desktop.in.in
- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
- data/meson.build
- meson.build
- src/exm-application.c
- src/exm-error-dialog.c
- src/exm-window.blp
- src/exm-window.c
Over the last cycles, apps added to GNOME core are not using the suffix in their names for development versions. Instead, they are adding a suffix to the app version following the running commit. Since it simplifies build files a bit and translators work, let's go that route as well.
> build: Use version suffix instead of name suffix

- data/com.mattjakeman.ExtensionManager.desktop.in.in
- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
- Mark release descriptions as untranslatable (1)
- Remove keywords that already presented in the desktop file (2)
---
1) GNOME automatically excludes release descriptions on Damned Lies (GNOME Translation Platform). It's a good practice to follow the GNOME way. This can streamline the translation process, allowing translators to focus their efforts on more critical and user-facing aspects of the application.
2) More information: https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/#icons-and-categories
> appdata: Update appdata

- src/exm-extension-row.blp
Fixes some cases where error labels could force the horizontal scrollbar to show when the width of the application window was small.
| master  | PR |
| ------------- | ------------- |
| ![](https://github.com/mjakeman/extension-manager/assets/42654671/7ee63cf3-0442-4e58-9a18-99afa0592cff) | ![](https://github.com/mjakeman/extension-manager/assets/42654671/c87ab81b-262b-41a0-b85c-684cf485d88d) |
> extension-row: Set error label wrap mode to word_char

- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
AppStream now recommends a reverse-DNS name, see https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer
Also, drop developer_name tag as Flathub has already switched to libappstream, see https://docs.flathub.org/blog/improved-build-validation
> metainfo: Fix developer id

- src/exm-application.c
- src/exm-comment-dialog.blp
- src/exm-comment-dialog.c
- src/exm-comment-dialog.h
- src/exm-detail-view.c
- src/exm-upgrade-assistant.blp
- src/exm-upgrade-assistant.c
- src/exm-upgrade-assistant.h
- src/exm-window.c
Requires `master` runtime-version.
Following https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/migrating-to-adaptive-dialogs.html
> Port to libadwaita 1.5 widgets

- src/exm-error-dialog.c
OS name and version also help us identify if the distribution method is Flatpak by showing the runtime.
Close https://github.com/mjakeman/extension-manager/issues/329
> error-dialog: Add OS info, GTK and Libadwaita versions

- src/exm-detail-view.c
- src/exm-zoom-picture.c
- src/exm-zoom-picture.h
See https://developer.gnome.org/hig/reference/keyboard.html#view-options
~It would fit better if it was in `zoom-picture` but it doesn't work there. I guess there is something in the event propagation that I'm not getting.~
> detail-view: Add zoom shortcuts

- README.md
- po/README.md
> Weblate preparations

- src/exm-installed-page.blp
- src/style.css
Workaround for https://gitlab.gnome.org/GNOME/gtk/-/issues/5309, the fix is from https://gitlab.gnome.org/GNOME/gtk/-/issues/5309#note_1692955
Fix https://github.com/mjakeman/extension-manager/issues/299
> installed-page: Fix sharp bottom corners of placeholders

- po/POTFILES
- src/exm-detail-view.blp
- src/exm-detail-view.c
- src/exm-screenshot-view.blp
- src/exm-screenshot-view.c
- src/exm-screenshot-view.h
- src/exm-window.blp
- src/exm.gresource.xml.in
- src/meson.build
- src/style.css
Fixes
> - [ ] Pop the image back in from fullscreen
in #485
> detail-view: Split screenshot overlay into its own view

- src/exm-detail-view.c
When viewing the details of an extension and it resulted in error, you could see the title of the extension seen just before.
Regression from #588
> detail-view: Ensure extension title is correct

- data/com.mattjakeman.ExtensionManager.desktop.in.in
The value type of the Keywords key is localestring(s), so translators can translate this string:
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
However, they must keep the separator semicolons as it is, so explicit that instead.
> desktop: Update translators comment

- po/extension-manager.pot
- src/exm-window.blp
Although there are more access keys throughout the UI, the ones in the main menu seem to be where there is the most overlap.
> Document access keys' translation

- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
It appears that the appstream project no longer supports `translatable=no` properties, and gettext extract the `translatable=no` marked strings as translatable.
I opened an issue to inform about the situation, but `translatable=no` properties are not accepted by developers. You can find the issue here: https://github.com/ximion/appstream/issues/623
**Please test your script or string extraction process before merging this PR.**
> In MetaInfo files, each individual paragraph of a description
> (or enumerated entry) is translated individually, however,
> you can only exclude the complete block from being translated
> by adding `translate="no"` to the description element.
Source: https://freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html
> appdata: `translate=no` properties

- src/exm-upgrade-assistant.blp
Using the style applied to list boxes in installed-page. Missed in #598.
> upgrade-assistant: Fix boxed list style

- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
This should fix the app icon breakage in GNOME Software after the switch to libappstream on Flathub's side.
> metainfo: Fix id

- src/exm-installed-page.blp
The current layout is mostly the same as the one we can achieve with them. Despite their name, they can be used outside of AdwPreferencesDialog resulting in a simpler widget tree.
Took the chance to run Blueprint's formatter.
> installed-page: Use AdwPreferences* widgets

- src/exm-backtrace.c
The static functions are internal to file `exm-backtrace.c` and are only used to facilitate backtrace collection.  In build configurations with backtraces disabled (`meson setup -Dbacktrace=false`), `exm_backtrace_print()` will not call the static functions, so they are unused and thus need not be defined.
Previously, due to how the preprocessor macros were arranged, the static variables in this file would not be defined when backtraces are disabled; if any static functions use them, then builds with backtraces disabled would fail due to a compiler error like:
../extension-manager-0.5.1/src/exm-backtrace.c: In function ‘exm_backtrace_full_cb’:
../extension-manager-0.5.1/src/exm-backtrace.c:58:9: error: ‘frames_omitted_count’ undeclared (first use in this function)
58 | …
> backtrace: Define static functions only if `WITH_BACKTRACE`

- .github/workflows/update-pot.yml
It requires a workaround to run `on: push` to master branch. Details are https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs.
In my fork, I went with SSH keys option (https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-using-ssh-deploy-keys) and it's working now, see https://github.com/oscfdezdz/extension-manager/pull/8
> workflows: Create PR on translation template update

- src/exm-extension-row.blp
- src/exm-extension-row.c
https://github.com/mjakeman/extension-manager/issues/646
> Display info icon for Initialized/Inactive extension state

- src/exm-comment-tile.blp
- src/exm-comment-tile.c
- src/web/model/exm-comment.c
Some changes I had in local from a few weeks ago. The layout may not be optimal.
Uses `%x` format:
> the preferred date representation for the current locale without the time
> Add date to comment tiles

- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
See https://docs.flathub.org/blog/introducing-app-brand-colors/
Taken from homepage https://mattjakeman.com/apps/extension-manager.html
| Light | Dark |
| -------- | ------- |
| ![image](https://github.com/mjakeman/extension-manager/assets/42654671/5457eb57-7271-4e2d-a05c-cd53d17aa72c) | ![image](https://github.com/mjakeman/extension-manager/assets/42654671/4a47e1fa-cffc-4869-916d-194be4d03455) |
> metainfo: Add brand colors

- src/exm-installed-page.c
Makes it possible to uninstall extensions when the global switch is disabled.
~Untested for GNOME Shell versions lower than 46.~ Works as expected.
Helps #340
Close #260
> installed-page: Keep rows sensitive when global switch is off

- src/exm-detail-view.c
- src/exm-info-bar.c
- src/exm-window.c
Something has changed upstream that causes it to generate criticals and not work, not sure about the details but these changes make it work again using the development manifest.
See https://stackoverflow.com/questions/24235937/custom-gtk-widget-with-template-ui#comment53693581_29363948
> app: Fix criticals in master runtime

- data/icons/hicolor/scalable/actions/zoom-in-symbolic.svg
- data/icons/hicolor/scalable/actions/zoom-out-symbolic.svg
- src/exm-help-overlay.blp
- src/exm-window.blp
- src/exm.gresource.xml.in
- src/meson.build
> app: Add back help overlay

- src/exm-extension-row.c
- src/local/exm-extension.c
- src/local/exm-manager.c
If available, it will be displayed to the user along with the version field.
At the moment, it is only available for installed extensions. For remote ones, we have to switch to the new API.
Helps #515
> local: Add support for version-name

- src/exm-comment-tile.c
- src/exm-rating.c
The code is copied from other widgets such as `ExmBrowsePage` or `ExmCommentDialog` among others. The warnings can be observed (without these changes) when opening and closing the detail view.
> Fix warnings when finalizing with remaining child widgets

- .github/workflows/update-pot.yml
- README.md
- build-aux/com.mattjakeman.ExtensionManager.Devel.json
- build-aux/com.mattjakeman.ExtensionManager.json
- src/exm-application.c
- src/exm-comment-tile.blp
- src/exm-comment-tile.c
- src/exm-detail-view.blp
- src/exm-utils.c
- src/exm-utils.h
- src/meson.build
- src/web/model/exm-comment.c
As mentioned in https://github.com/mjakeman/text-engine/issues/40#issuecomment-2352937530. The code is adapted from the `import-html` source file of text-engine, drops its dependency and makes us depend on libxml2 which is in GNOME SDK.
Close #163
Close #687
> Simple HTML viewer

- src/exm-browse-page.c
- src/exm-browse-page.h
- src/exm-detail-view.c
- src/exm-help-overlay.blp
- src/exm-installed-page.blp
- src/exm-installed-page.c
- src/exm-installed-page.h
- src/exm-upgrade-assistant.c
- src/exm-window.blp
- src/exm-window.c
- src/exm-window.h
- src/local/exm-manager.c
It should be a step forward for unified search in the future, rather than a blocker, hopefully.
~Marked as draft as the code has plenty of room for improvement.~
| Results page  | Empty page |
| ------------- | ------------- |
| ![Screenshot From 2024-09-17 10-55-59](https://github.com/user-attachments/assets/c80285e3-3c60-48ef-b684-23e750aa08dd) | ![Screenshot From 2024-09-17 10-56-09](https://github.com/user-attachments/assets/7f4499e7-faa8-467b-8144-cb7fdc715658) |
Close #8
> Add local search

- src/exm-comment-dialog.blp
- src/exm-detail-view.blp
- src/exm-upgrade-assistant.blp
- src/exm-upgrade-assistant.c
- Replaces boxes with status pages, thus enabling their use and simplifying widget trees.
- Declares the spinners first in the blueprints to prevent a Gtk warning about unloadable images. This warning occurs when the widgets are directly declared in the AdwStatusPage property.
> general: Use AdwSpinnerPaintable where possible

- build-aux/com.mattjakeman.ExtensionManager.Devel.json
- build-aux/com.mattjakeman.ExtensionManager.json
- src/exm-comment-dialog.c
Partially reverts a389ff389ad09f8bc13f77140e890166ea53d9fc which was mostly a workaround and uses GObject's dispose to cancel the ongoing request if the dialog is closed before it is completed.
Fix https://github.com/mjakeman/extension-manager/issues/310
> comment-dialog: Fix crash on close while loading

- src/exm-extension-row.blp
- src/exm-extension-row.c
- src/style.css
This replaces the GtkGrid with a series of AdwActionRow for the extension description, version, and error message. This makes the design more modern and in line with the rest of the app and other GNOME apps, and makes the app fit on smartphones.
Fixes https://github.com/mjakeman/extension-manager/issues/767
⚠️ I'm not sure if the `multiline` style class should change the whole row (hence the title and the description) or the description only. It's trivial to fix, just replace `.multiline {` by `.multiline .subtitle {` in the CSS file. Right now it affects both, which IMO looks a biut better, but I don't have a strong opinion. What do you think?
Are are screenshots of before and after this MR.
> extension-row: Use AdwActionRow for description

- src/exm-browse-page.c
- src/exm-detail-view.c
- src/exm-install-button.c
- src/exm-search-row.c
- src/exm-search-row.h
- src/exm-types.h
- src/exm-window.c
- src/local/exm-manager.c
- src/local/exm-manager.h
From the main commit:
```
Introduces a new installing state that is set before activating
`ext.install` action. To deal with cancellations, a new `install-status`
signal is added to ExmManager which is emitted whenever it happens and
reverts the button state to the last one it had, either default or
unsupported.
ExmSearchRow drops `is-installed` and `is-supported` properties in favor
of a new `manager` property to connect to ExmManager's `install-status`
signal.
```
Fix #673
> Disable install button during installation

- src/exm-extension-row.blp
- src/exm-extension-row.c
- src/exm-installed-page.c
- src/exm-upgrade-result.c
- src/local/exm-extension.c
- src/local/exm-manager.c
Shows the session modes in a new row. It should also help with https://github.com/mjakeman/extension-manager/pull/773 since this approach doesn't rely on extensions' state, which is giving some issues there.
It also adds url and donations properties for future use.
About how the switch status is shown, I have checked again and we don't differ on the behavior with Extensions, so #646 could have been closed a while ago I think. I'll still take the opportunity and close it with these changes.
Close #646
> extension-row: Add Session Modes row

- src/exm-extension-row.c
- src/exm-extension-row.h
- src/exm-installed-page.blp
- src/exm-installed-page.c
- src/local/exm-extension.c
- src/local/exm-extension.h
- src/local/exm-manager.c
The items-changed signal is now emitted without adding or removing items to the model from ExmManager and is connected after binding the manager in ExmInstalledPage from where the callback saves, emits items-changed adding and removing as done before in ExmManager, and restores focus.
This approach allows us to keep binding GtkListBox to the extensions model and not having to manage the changes manually.
Fix https://github.com/mjakeman/extension-manager/issues/220
> installed-page: Save extension's toggle focus on state changes

- src/exm-comment-dialog.blp
- src/exm-detail-view.blp
- src/exm-detail-view.c
We retrieve reviews/comments in the details view and the comment dialog using different queries. Because we do not know the total count until querying all of them in the dialog, we have to display the button for extensions with exactly five or more reviews/comments, rather than strictly more than five.
Also rewords strings containing comment or review to use both terms as they are both possible and adds pill style to the button.
Close #781
> detail-view: Hide "Show All Reviews" button when unneeded

- build-aux/com.mattjakeman.ExtensionManager.json
- src/meson.build
By setting a minimum version we help to identify more easily what the problem is when trying to build with older versions.
It requires updating every time we use widgets introduced in the latest versions.
We don't need to specify the version of any further dependencies since libadwaita already increments the minimum required version of GTK and we don't depend on anything specific of the latest versions.
Helps #792
> build: Specify the minimum required version of libadwaita

- src/exm-application.c
- src/exm-window.c
- src/local/exm-manager.c
- src/web/model/exm-shell-version-map.c
Instead of g_str_equal which is still used for hash table comparisons as recommended in the documentation.
Fix #798
> general: Use g_strcmp0 for null safe string comparison

- src/exm-upgrade-assistant.blp
- src/exm-upgrade-assistant.c
GNOME itself does not support extensions, it is the extensions that have to be marked as compatible with specific versions of GNOME.
Fix #802
> upgrade-assistant: Reword results page heading
