- po/es.po
- po/extension-manager.pot
- src/exm-window.blp
Make strings from #15 translatable and update po files.
> po: Update translation files with new strings

- README.md
We now support translations. Update the README accordingly.
> Update README with l10n information

- src/exm-window.c
- src/local/exm-manager.c
- Refactor exm-manager to granually update the list models rather than fully regenerate them.
- This should result in less wasted performance, less visual flicker, and simpler gui code.
- It will also enable a global on/off extensions toggle, as performance was an obstacle to this beforehand.
This is another change which touches a lot of core features and will require further testing to ensure nothing has regressed.
Depends on #37
> Selectively update list model when extension state changes

- po/pt_BR.po
> po: Update Brazilian Portuguese translation

- po/pt_BR.po
It's arrived late but it arrived. Sorry!
> po: Update to newest Brazilian PT translation

- po/tr.po
It's done but looks like you'll need to delete the "Localised into seven languages" strings from .pot and .po files because translations to other languages ​​keep increasing.
> Add Turkish Translation

- po/de.po
Updated and fixed German Translation
> Updated for v0.2.0 release an minor fixes.

- po/LINGUAS
Adds Hungarian, reorders to be alphabetical
> po: Update LINGUAS file

- po/LINGUAS
- po/ru_RU.po
Russian translation by @Danik2343
> Add Russian Translation

- src/exm-search-row.c
> fix character escaping in title

- po/LINGUAS
- po/fr.po
French translation contributed by @PaxtonGround
> Add French Translation

- po/de.po
Added translator credit, 0.2.2 changelog and found a more fitting word for "recent" in the used context.
> Update German 

- po/LINGUAS
- po/nb.po
The string “Localised into seven languages” seems odd…
I can add Norwegian (nynorsk) later.
> po: Add Norwegian (bokmal) Translation

- po/ja.po
> Update Japanese Translations

- po/LINGUAS
- po/nn.po
Norwegian Nynorsk translation created from the Bokmål version, with help of Apertium.
> Add Norwegian Nynorsk translation

- data/com.mattjakeman.ExtensionManager.gschema.xml.in
- data/meson.build
- meson.build
- src/exm-application.c
- src/exm-release-notes-dialog.blp
- src/exm-release-notes-dialog.c
- src/exm-release-notes-dialog.h
- src/exm-window.blp
- src/exm-window.c
- src/exm.gresource.xml
- src/meson.build
- src/release-notes.txt
- Notifies the user when an update is installed
- Prompts them to view the release notes
- Only shows on first run
- Adds option to dropdown menu
Fixes #129
> Add in-app release notes feature

- NEWS
- data/com.mattjakeman.ExtensionManager.appdata.xml.in.in
- meson.build
- src/release-notes.txt
Finally... Just in time for 42 :eyes:
> project: Release version 0.3.0

- NEWS
- src/exm-application.c
- src/exm-installed-page.c
- src/exm-window.c
- src/local/exm-extension.c
- Remove reference to placeholder labels feature
- Better memory management/safety checks
- Do not escape description/name text
- Fixes #143 
- General code cleanup
> Further fixes for 0.3

- po/ru_RU.po
Updated Russian Translation [100 % + minor fix]
> Updated Russian Translation [100 % + minor fix]

- po/ru_RU.po
Updated Russian (very minor fixes)
> Updated Russian (very minor fixes)

- po/fr.po
Needs a newline otherwise both entries will be concatenated
> Fix translator credits for French translation

- po/pt_BR.po
> po: Update Brazilian Portuguese translations

- src/exm-window.c
> Set window title

- po/oc.po
> Update oc.po: 100%

- NEWS
- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
- meson.build
- src/release-notes.txt
> project: Release version 0.3.1

- po/hu.po
Fixed some typos and wrong strings.
> Some fixes

- po/LINGUAS
- po/pt.po
Add pt to LINGUAS and add pt.po translation file
> Add Portuguese translation

- po/zh_TW.po
Fix typos, formatting and match official GNOME translations
> Update Traditional Chinese translations

- po/LINGUAS
- po/et.po
Added Estonian (et) translation to the project.
> po: Added Estonian translation

- src/exm-browse-page.blp
- src/exm-comment-dialog.blp
- src/exm-detail-view.blp
- src/exm-extension-row.blp
- src/exm-installed-page.blp
- src/style.css
Some changes to padding to better fit a mobile form factor
> Mobile Tweaks

- src/exm-detail-view.blp
- src/exm-extension-row.blp
- src/exm-installed-page.blp
- src/exm-installed-page.c
- src/exm-search-row.blp
- src/exm-window.blp
- src/exm-window.c
- src/style.css
A set of changes in response to [GNOME Circle feedback](https://gitlab.gnome.org/Teams/Circle/-/issues/114).
Fixes #164
Fixes #80
Fixes #204 
Part of #163
> Fixes for GNOME Circle

- src/meson.build
> Add gio-unix-2.0 dependency

- src/exm-browse-page.c
- src/web/exm-search-provider.c
> Fix crash when no results are found

- src/exm-extension-row.blp
- Flat style as per HIG
- Add a tooltip
Fixes #270
> Use 'flat' style for prefs button and add tooltip

- po/LINGUAS
- po/ta.po
Adding Tamil Translation to `po` directory.
Signed-off-by: K.B.Dharun Krishna <kbdharunkrishna@gmail.com>
> po: Add Tamil Translation

- src/exm-application.c
- src/exm.gresource.xml
Now that we store icons as resources, find the search path properly
> Add icon search path

- README.md
- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
- po/POTFILES
- po/README.md
- po/extension-manager.pot
- po/print-source-files.sh
- src/exm-application.c
- src/exm-browse-page.c
- src/exm-detail-view.c
- src/exm-extension-row.c
- src/exm-installed-page.c
- src/exm-upgrade-assistant.blp
- src/exm-upgrade-assistant.c
- src/exm-upgrade-result.c
- src/exm-upgrade-result.h
- src/meson.build
- src/style.css
> Tweaks for 0.4

- com.mattjakeman.ExtensionManager.Devel.json
- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
- src/res/release-notes.txt
> Release version 0.4

- po/et.po
As with any new update, comes new words that, hereby, have to be translated.
> Updated Estonian Translation

- po/el.po
what the title says 
have a nice afternoon mjakeman
> Updated Greek Translation

- po/ru_RU.po
Update Russian Language Translation
> Update Russian Language Translation

- po/extension-manager.pot
- po/nl.po
Updated translation files and Dutch translation.
> Update Dutch translation

- README.md
Centered the _Title_, _Description_ and _Screenshots_
> README.md: Minor Changes

- README.md
> Document how to build from source (#357)

- README.md
Probably about time we had one :)
> Add matrix room to README.md

- data/com.mattjakeman.ExtensionManager.desktop.in.in
Thanks to RioZuni for pointing out the absence.
Fixes #427
> Add desktop file comment

- src/web/exm-search-provider.c
> search-provider: Fix sorting by recents

- data/com.mattjakeman.ExtensionManager.desktop.in.in
> app: Add desktop keywords

- po/vi_VN.po
> po: Add Vietnam Translation

- src/exm-application.c
- src/exm-backtrace.c
- src/exm-browse-page.blp
- src/exm-browse-page.c
- src/web/exm-comment-provider.c
- src/web/exm-search-provider.c
- src/web/exm-search-provider.h
A long time coming:
- Fixes (hopefully for good) the race condition in search
- Removes the popularity search type (as it doesn't work) 
- Some minor g_info -> g_print cleanup
Fixes #397
> Fix race condition and remove broken popularity search

- README.md
- po/README.md
- po/extension-manager.pot
So, I started initial work on how future "Translation Guide" section might look like. I'm not the best with markdown and with English, so better help with wording, typos, etc is appreciated.
> Add "Translation Guide" to README

- src/exm-extension-row.blp
> Change padding and sizes for row with Details & Remove buttons

- po/oc.po
> i18n: Update for Occitan

- po/LINGUAS
- po/ko.po
Add Korean Translation
(Add ko.po&Edit LINGUAS)
> Add Korean Translation

- po/ar.po
> Update Arabic translation

- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
> metainfo: Update

- po/extension-manager.pot
> po: Update template

- src/exm-browse-page.blp
- src/exm-browse-page.c
- src/exm-comment-tile.blp
- src/exm-comment-tile.c
- src/exm-installed-page.blp
- src/exm-installed-page.c
- src/exm-search-row.blp
- src/exm-search-row.c
- src/exm-upgrade-assistant.blp
- src/exm-upgrade-assistant.c
- src/exm-window.blp
I made sure none of these changes conflict with `gnome-circle` branch.
> Blueprint tweaks

- po/extension-manager.pot
- src/exm-browse-page.blp
- src/exm-comment-dialog.blp
- src/exm-detail-view.blp
- src/exm-detail-view.c
- src/exm-detail-view.h
- src/exm-screenshot.blp
- src/exm-upgrade-assistant.blp
- src/exm-upgrade-assistant.c
- src/exm-window.blp
- src/exm-window.c
See commit messages for more details.
Some of the UI changes:
[Screencast.webm](https://github.com/mjakeman/extension-manager/assets/42654671/80e0c635-e6ed-489c-a06e-fd1f24fa88cf)
> UI and UX tweaks

- data/com.mattjakeman.ExtensionManager.gschema.xml.in
- src/exm-application.c
- src/exm-window.blp
Close https://github.com/mjakeman/extension-manager/issues/102
> window: Save window state

- src/exm-detail-view.c
Fix https://github.com/mjakeman/extension-manager/issues/612
> detail-view: Add null checks for version parsing

- src/exm-backtrace.c
Close https://github.com/mjakeman/extension-manager/issues/411
> backtrace: Collate 'null' messages

- .github/workflows/update-pot.yml
I tested it in a fork (https://github.com/oscfdezdz/extension-manager) as I wasn't sure if it would require changing repository settings. It didn't 🙃 
Uses `ubuntu-latest` image and `debian:sid` container, as any other combination would add metainfo strings that are marked as untranslatable. Probably due to differences in appstream versions.
> workflows: Add translation template updater

- src/exm-comment-dialog.c
Fix https://github.com/mjakeman/extension-manager/issues/310
> comment-dialog: Fix crash on close while loading

- .github/ISSUE_TEMPLATE/bug_report.md
- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
- meson.build
> Release v0.5.1

- src/exm-extension-row.c
- src/exm-installed-page.c
Following #647.
We may have to change the return values.
> Return fixes

- src/exm-upgrade-assistant.c
This prolly needs more work to work with older versions.
> Index as pointer

- src/exm-detail-view.c
- src/exm-window.c
> Fix some warnings

- po/ko.po
Fixed some mistakes of translation.
> Update Korean Translation

- .github/workflows/main.yml
Helps to unblock Translations workflow while a solution is found.
> workflows: Add option to run CI manually

- build-aux/com.mattjakeman.ExtensionManager.Devel.json
- src/exm-backtrace.c
- src/exm-comment-tile.c
With these changes CI should pass again.
> Adapt to text-engine changes

- src/exm-browse-page.blp
- src/exm-browse-page.c
- src/exm-detail-view.blp
- src/exm-error-dialog.blp
- src/exm-extension-row.blp
- src/exm-install-button.c
- src/exm-installed-page.blp
- src/exm-installed-page.c
- src/exm-upgrade-assistant.c
- src/exm-window.c
See https://developer.gnome.org/hig/guidelines/writing-style.html
Changes for the next major version.
> app: Better compliance with HIG writing style

- src/exm-browse-page.blp
For better network efficiency.
Close https://github.com/mjakeman/extension-manager/issues/692
> browse-page: Increase search-delay value

- src/exm-window.blp
- src/exm-window.c
| Installed Page  | Browse Page |
| ------------- | ------------- |
| ![Screenshot](https://github.com/user-attachments/assets/c489ffe2-1302-4da8-ad4f-8cc795cc6eab) | ![Captura desde 2024-08-04 01-43-06](https://github.com/user-attachments/assets/cae7f125-5b9e-48df-ab58-653ad9da2883) |
> window: Show badge number when updates are available

- src/exm-browse-page.blp
- src/exm-browse-page.c
- src/exm-browse-page.h
Fix https://github.com/mjakeman/extension-manager/issues/355
> browse-page: Enable type-ahead search

- .github/workflows/update-pot.yml
> workflows: Add missing libxml2 dependency

- build-aux/com.mattjakeman.ExtensionManager.json
- src/exm-browse-page.blp
- src/exm-browse-page.c
Also removes an unused GtkScrolledWindow.
Fix https://github.com/mjakeman/extension-manager/issues/753
> browse-page: Preserve scroll position on 'Load More Results'

- src/exm-application.c
- src/exm-backtrace.c
- src/exm-browse-page.c
- src/exm-comment-dialog.c
- src/exm-detail-view.c
- src/exm-extension-row.c
- src/exm-install-button.c
- src/exm-installed-page.c
- src/exm-rating.c
- src/exm-screenshot-view.c
- src/exm-screenshot.c
- src/exm-upgrade-result.c
- src/exm-window.c
- src/exm-zoom-picture.c
- src/local/exm-extension.c
- src/local/exm-manager.c
- src/web/exm-comment-provider.c
- src/web/exm-data-provider.c
- src/web/exm-image-resolver.c
- src/web/exm-request-handler.c
- src/web/exm-search-provider.c
- src/web/model/exm-search-result.c
> Fix all warnings

- src/exm-search-row.blp
- src/exm-window.blp
> Minor UI cleanups

- .github/ISSUE_TEMPLATE/bug_report.md
- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
- meson.build
Bug fixes and translation updates :smile:
> Update for v0.6.1

- src/exm-browse-page.c
- src/exm-comment-dialog.c
- src/exm-detail-view.c
- src/exm-upgrade-assistant.c
- src/web/exm-image-resolver.c
- src/web/exm-request-handler.c
> Fix HTTP responses handling

- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
- src/exm-browse-page.blp
- src/exm-browse-page.c
- src/exm-browse-page.h
- src/exm-detail-view.blp
- src/exm-detail-view.c
- src/exm-extension-row.blp
- src/exm-info-bar.blp
- src/exm-installed-page.c
- src/exm-installed-page.h
- src/exm-upgrade-assistant.blp
- src/exm-upgrade-assistant.c
- src/exm-window.blp
- src/exm-window.c
- src/exm-window.h
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/edbc1ec9-1ea4-40c3-b64f-65da5ffc018c) | ![image](https://github.com/user-attachments/assets/9ffedbc5-550a-41e5-94de-38cd3c6f6c1d) |
| ![image](https://github.com/user-attachments/assets/23345695-8d0d-4d59-82f1-c05b9c6cf504) | ![image](https://github.com/user-attachments/assets/2f9243a5-f12d-4b07-a9cb-e3fed8bbc55d) |
> Various tweaks

- src/exm-comment-tile.blp
- src/exm-error-dialog.blp
- src/exm-error-dialog.c
- src/exm-upgrade-assistant.blp
- src/style.css
> error-dialog: Refresh style

- .github/ISSUE_TEMPLATE/bug_report.md
- data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in
- meson.build
> Update for v0.6.2

- src/exm-application.c
- src/exm-backtrace.c
> Fix app closure

- src/exm-backtrace.h
- src/exm-comment-dialog.h
- src/exm-comment-tile.h
- src/exm-error-dialog.c
- src/exm-error-dialog.h
- src/exm-extension-row.h
- src/exm-rating.h
- src/exm-screenshot-view.h
- src/exm-screenshot.h
- src/exm-search-row.c
- src/exm-upgrade-assistant.h
- src/exm-utils.c
- src/exm-utils.h
- src/exm-zoom-picture.h
- src/local/exm-extension.h
- src/web/exm-comment-provider.h
- src/web/exm-image-resolver.h
- src/web/exm-request-handler.h
- src/web/model/exm-comment.c
- src/web/model/exm-comment.h
The missing files are barely modified and at this rate we will never add the license to their headers.
Close #235
> project: Add and update license headers in missing files
